### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [abocianowski/AttributesJoinByLine#1]
# Problem

![page](https://user-images.githubusercontent.com/2510900/59742720-9c6da500-926e-11e9-84df-b68144887996.png)

**Comment by abocianowski** [comment]
Hi, Thank You for reporting. 
I've added a home page to metadata
![image](https://user-images.githubusercontent.com/50774139/59743662-07b87680-9271-11e9-8667-1868b82c34e3.png)
